web:
  image: nginx
  volumes:
   - ./html:/usr/share/nginx/html:ro
   - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
   - ./conf/conf.d:/etc/nginx/conf.d:ro
   - /etc/letsencrypt/live/www.fluxcapdata.net/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
   - /etc/letsencrypt/live/www.fluxcapdata.net/privkey.pem:/etc/ssl/keys/privkey.pem:ro
  ports:
   - "80:80"
   - "443:443"
  command: "nginx -g 'daemon off;'"
