web:
  image: nginx
  volumes:
   - /etc/letsencrypt/live/www.fluxcapdata.net/fullchain.pem:/etc/ssl/certs/fullchain.pem
   - /etc/letsencrypt/live/www.fluxcapdata.net/privkey.pem:/etc/ssl/keys/privkey.pem
   - /var/run:/var/run
   - ./conf/nginx.conf:/etc/nginx/nginx.conf
   - ./conf/conf.d:/etc/nginx/conf.d
   - ./html:/usr/share/nginx/html
  ports:
   - "80:80"
   - "443:443"
  command: "nginx -g 'daemon off;'"
